# Generated by Django 6.0.4 on 2026-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
