# Generated by Django 6.0.4 on 2026-07-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='ftc_screenshot_b64',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
